title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://genicsblog.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  genicsblog
github_repo: http://github.com/genicsblog/genicsblog.github.io
permalink: /:title

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postcss
  - jekyll-minifier
  - jekyll-archives

include: 
  - _pages

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - postcss.config.js
  - tailwind.config.js
  - package.json
  - package-lock.json
  - README.md

postcss:
  cache: false

jekyll-minifier:
  exclude: ["assets/css/theme.css", "assets/js/prism.js"]