title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://genicsblog.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  genicsblog
github_repo: http://github.com/genicsblog/genicsblog.github.io
permalink: /:title

collections:
  author_pages:
    permalink: /author/:name
    output: true

pagination:
  enabled: true
  per_page: 1
  permalink: '/page/:num/'
  title: ':title - page :num'
  sort_field: 'date'
  sort_reverse: true

autopages:
  enabled: true

  categories: 
    layouts: 
      - 'default.html'
    title: 'Posts in category :cat'
    permalink: '/category/:cat'
    silent: false
    slugify:
      mode: 'default'
      case: true

  collections:
    enabled: false

  tags:
    layouts: 
      - 'default.html'
    title: 'Posts tagged with :tag'
    permalink: '/tag/:tag'
    silent: false
    slugify:
      mode: 'default'
      case: true
      
# Build settings
plugins:
  - jemoji
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postcss
  - jekyll-minifier
  - jekyll-archives
  - jekyll-paginate-v2

include: 
  - _pages
  - .nojekyll

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - postcss.config.js
  - tailwind.config.js
  - package.json
  - package-lock.json
  - README.md

postcss:
  cache: false

jekyll-minifier:
  exclude: ["sitemap.xml", "feed.xml", "assets/css/theme.css", "assets/js/prism.js"]