name: Publish site

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.5
        bundler-cache: true

    - uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Add .nojekyll file
      run: touch .nojekyll

    - name: Install npm dependencies
      run: npm install

    - name: Build production jekyll site
      run: JEKYLL_ENV=production NODE_ENV=production bundle exec jekyll build

    - name: Deploy to gh-pages
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: _site
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
