name: Publish site

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          files:
            - '_contributors/**'
            - '_data/**'
            - '_drafts/**'
            - '_includes/**'
            - '_layouts/**'
            - '_pages/**'
            - '_plugins/**'
            - '_posts/**'
            - '_series/**'
            - 'assets/**'
            - '_config.yml'
            - 'search.json'
            - 'tailwind.config.js'
            - 'postcss.config.js'

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.5
        bundler-cache: true

    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install npm dependencies
      run: npm install

    - name: Install python dependencies
      run: |
        pip install nltk textblob html2text beautifulsoup4
        python -m nltk.downloader brown punkt

    - name: Build production jekyll site
      if: steps.changes.outputs.files == 'true'
      run: JEKYLL_ENV=production NODE_ENV=production bundle exec jekyll build

    - name: Fix search.json
      if: steps.changes.outputs.files == 'true'
      run: |
        python _scripts/analyse-content.py

    - name: Deploy to gh-pages
      if: steps.changes.outputs.files == 'true'
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: _site
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
